[package]
name = "backup_md5"
version = "0.1.0"
edition = "2021"

[dependencies]
walkdir = "2.3"
md5 = "0.7.0"
chrono = "0.4"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
anyhow = "1.0"

[dev-dependencies]
tempfile = "3.3"